### ISSUE TITLE
Alternative paths not working

### ISSUE THREAD

**Issue by profseth** [briochemc/GEOTRACES.jl#7]
The option of placing Geotraces data in an alternative folder, and then changing the path, which is described in the documentation using the line:

ENV["GEOTRACES_IDP2017_PATH"] = <path_to_your_GEOTRACES_data>

does not work for me. I'm not sure what the underlying problem is...

**Comment by briochemc** [comment]
Solved the angry way: I've removed that piece of documentation for v0.3 for IDP21! Now users *must* place the data where it is expected by GEOTRACES.jl.

Because GEOTRACES itself does not provide a direct URL to its data and thus implicitly requires its human users to manually click a download button (and then manually chose where to download and unpack the data on their local machines), then said humans shall be expected to manually move the data and unpack it in the right place! 😅
